# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
rojo = "rojo-rbx/rojo@7.6.1"
stylua = "johnnymorganz/stylua@2.3.1"
wally = "upliftGames/wally@0.3.2"
rbxcloud = "Sleitnick/rbxcloud@0.17.0"
lune = "lune-org/lune@0.10.4"
selene = "Kampfkarren/selene@0.30.0"
asphalt = "jackTabsCode/asphalt@1.2.0"
